#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCT_May
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCH")]
	public partial class DaiLyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietHoaDon(ChiTietHoaDon instance);
    partial void UpdateChiTietHoaDon(ChiTietHoaDon instance);
    partial void DeleteChiTietHoaDon(ChiTietHoaDon instance);
    partial void InsertDaiLy(DaiLy instance);
    partial void UpdateDaiLy(DaiLy instance);
    partial void DeleteDaiLy(DaiLy instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertThanhToan(ThanhToan instance);
    partial void UpdateThanhToan(ThanhToan instance);
    partial void DeleteThanhToan(ThanhToan instance);
    #endregion
		
		public DaiLyDataContext() : 
				base(global::QLCT_May.Properties.Settings.Default.QLCHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DaiLyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DaiLyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DaiLyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DaiLyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<DaiLy> DaiLies
		{
			get
			{
				return this.GetTable<DaiLy>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<ThanhToan> ThanhToans
		{
			get
			{
				return this.GetTable<ThanhToan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _SoLuong;
		
		private int _SoHoaDon;
		
		private int _MaSanPham;
		
		private EntityRef<HoaDon> _HoaDon;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnSoHoaDonChanging(int value);
    partial void OnSoHoaDonChanged();
    partial void OnMaSanPhamChanging(int value);
    partial void OnMaSanPhamChanged();
    #endregion
		
		public ChiTietHoaDon()
		{
			this._HoaDon = default(EntityRef<HoaDon>);
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SoHoaDon
		{
			get
			{
				return this._SoHoaDon;
			}
			set
			{
				if ((this._SoHoaDon != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoHoaDonChanging(value);
					this.SendPropertyChanging();
					this._SoHoaDon = value;
					this.SendPropertyChanged("SoHoaDon");
					this.OnSoHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_HoaDon", ThisKey="SoHoaDon", OtherKey="SoHoaDon", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._SoHoaDon = value.SoHoaDon;
					}
					else
					{
						this._SoHoaDon = default(int);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietHoaDon", Storage="_SanPham", ThisKey="MaSanPham", OtherKey="MaSanPham", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._MaSanPham = value.MaSanPham;
					}
					else
					{
						this._MaSanPham = default(int);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DaiLy")]
	public partial class DaiLy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDaiLy;
		
		private string _TenChuDaiLy;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _HinhThucThanhToan;
		
		private System.Nullable<int> _NoDauKy;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<ThanhToan> _ThanhToans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDaiLyChanging(int value);
    partial void OnMaDaiLyChanged();
    partial void OnTenChuDaiLyChanging(string value);
    partial void OnTenChuDaiLyChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnHinhThucThanhToanChanging(string value);
    partial void OnHinhThucThanhToanChanged();
    partial void OnNoDauKyChanging(System.Nullable<int> value);
    partial void OnNoDauKyChanged();
    #endregion
		
		public DaiLy()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._ThanhToans = new EntitySet<ThanhToan>(new Action<ThanhToan>(this.attach_ThanhToans), new Action<ThanhToan>(this.detach_ThanhToans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuDaiLy", DbType="NVarChar(255)")]
		public string TenChuDaiLy
		{
			get
			{
				return this._TenChuDaiLy;
			}
			set
			{
				if ((this._TenChuDaiLy != value))
				{
					this.OnTenChuDaiLyChanging(value);
					this.SendPropertyChanging();
					this._TenChuDaiLy = value;
					this.SendPropertyChanged("TenChuDaiLy");
					this.OnTenChuDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucThanhToan", DbType="Char(10)")]
		public string HinhThucThanhToan
		{
			get
			{
				return this._HinhThucThanhToan;
			}
			set
			{
				if ((this._HinhThucThanhToan != value))
				{
					this.OnHinhThucThanhToanChanging(value);
					this.SendPropertyChanging();
					this._HinhThucThanhToan = value;
					this.SendPropertyChanged("HinhThucThanhToan");
					this.OnHinhThucThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDauKy", DbType="Int")]
		public System.Nullable<int> NoDauKy
		{
			get
			{
				return this._NoDauKy;
			}
			set
			{
				if ((this._NoDauKy != value))
				{
					this.OnNoDauKyChanging(value);
					this.SendPropertyChanging();
					this._NoDauKy = value;
					this.SendPropertyChanged("NoDauKy");
					this.OnNoDauKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaiLy_HoaDon", Storage="_HoaDons", ThisKey="MaDaiLy", OtherKey="MaDaiLy")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaiLy_ThanhToan", Storage="_ThanhToans", ThisKey="MaDaiLy", OtherKey="MaDaiLy")]
		public EntitySet<ThanhToan> ThanhToans
		{
			get
			{
				return this._ThanhToans;
			}
			set
			{
				this._ThanhToans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.DaiLy = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.DaiLy = null;
		}
		
		private void attach_ThanhToans(ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.DaiLy = this;
		}
		
		private void detach_ThanhToans(ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.DaiLy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoHoaDon;
		
		private System.Nullable<System.DateTime> _NgayLapHoaDon;
		
		private System.Nullable<int> _MaDaiLy;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntityRef<DaiLy> _DaiLy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHoaDonChanging(int value);
    partial void OnSoHoaDonChanged();
    partial void OnNgayLapHoaDonChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapHoaDonChanged();
    partial void OnMaDaiLyChanging(System.Nullable<int> value);
    partial void OnMaDaiLyChanged();
    #endregion
		
		public HoaDon()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._DaiLy = default(EntityRef<DaiLy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SoHoaDon
		{
			get
			{
				return this._SoHoaDon;
			}
			set
			{
				if ((this._SoHoaDon != value))
				{
					this.OnSoHoaDonChanging(value);
					this.SendPropertyChanging();
					this._SoHoaDon = value;
					this.SendPropertyChanged("SoHoaDon");
					this.OnSoHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapHoaDon", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLapHoaDon
		{
			get
			{
				return this._NgayLapHoaDon;
			}
			set
			{
				if ((this._NgayLapHoaDon != value))
				{
					this.OnNgayLapHoaDonChanging(value);
					this.SendPropertyChanging();
					this._NgayLapHoaDon = value;
					this.SendPropertyChanged("NgayLapHoaDon");
					this.OnNgayLapHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="Int")]
		public System.Nullable<int> MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					if (this._DaiLy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="SoHoaDon", OtherKey="SoHoaDon")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaiLy_HoaDon", Storage="_DaiLy", ThisKey="MaDaiLy", OtherKey="MaDaiLy", IsForeignKey=true)]
		public DaiLy DaiLy
		{
			get
			{
				return this._DaiLy.Entity;
			}
			set
			{
				DaiLy previousValue = this._DaiLy.Entity;
				if (((previousValue != value) 
							|| (this._DaiLy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DaiLy.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._DaiLy.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaDaiLy = value.MaDaiLy;
					}
					else
					{
						this._MaDaiLy = default(Nullable<int>);
					}
					this.SendPropertyChanged("DaiLy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSanPham;
		
		private string _TenSanPham;
		
		private System.Nullable<int> _KichThuoc;
		
		private System.Nullable<int> _DonGiaTraCham;
		
		private System.Nullable<int> _DonGiaTraNgay;
		
		private System.Nullable<int> _DonGiaTraGop;
		
		private string _GhiChu;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSanPhamChanging(int value);
    partial void OnMaSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnKichThuocChanging(System.Nullable<int> value);
    partial void OnKichThuocChanged();
    partial void OnDonGiaTraChamChanging(System.Nullable<int> value);
    partial void OnDonGiaTraChamChanged();
    partial void OnDonGiaTraNgayChanging(System.Nullable<int> value);
    partial void OnDonGiaTraNgayChanged();
    partial void OnDonGiaTraGopChanging(System.Nullable<int> value);
    partial void OnDonGiaTraGopChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public SanPham()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(255)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuoc", DbType="Int")]
		public System.Nullable<int> KichThuoc
		{
			get
			{
				return this._KichThuoc;
			}
			set
			{
				if ((this._KichThuoc != value))
				{
					this.OnKichThuocChanging(value);
					this.SendPropertyChanging();
					this._KichThuoc = value;
					this.SendPropertyChanged("KichThuoc");
					this.OnKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaTraCham", DbType="Int")]
		public System.Nullable<int> DonGiaTraCham
		{
			get
			{
				return this._DonGiaTraCham;
			}
			set
			{
				if ((this._DonGiaTraCham != value))
				{
					this.OnDonGiaTraChamChanging(value);
					this.SendPropertyChanging();
					this._DonGiaTraCham = value;
					this.SendPropertyChanged("DonGiaTraCham");
					this.OnDonGiaTraChamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaTraNgay", DbType="Int")]
		public System.Nullable<int> DonGiaTraNgay
		{
			get
			{
				return this._DonGiaTraNgay;
			}
			set
			{
				if ((this._DonGiaTraNgay != value))
				{
					this.OnDonGiaTraNgayChanging(value);
					this.SendPropertyChanging();
					this._DonGiaTraNgay = value;
					this.SendPropertyChanged("DonGiaTraNgay");
					this.OnDonGiaTraNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaTraGop", DbType="Int")]
		public System.Nullable<int> DonGiaTraGop
		{
			get
			{
				return this._DonGiaTraGop;
			}
			set
			{
				if ((this._DonGiaTraGop != value))
				{
					this.OnDonGiaTraGopChanging(value);
					this.SendPropertyChanging();
					this._DonGiaTraGop = value;
					this.SendPropertyChanged("DonGiaTraGop");
					this.OnDonGiaTraGopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="MaSanPham", OtherKey="MaSanPham")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhToan")]
	public partial class ThanhToan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoPhieuThu;
		
		private System.Nullable<System.DateTime> _NgayLapPhieu;
		
		private System.Nullable<int> _SoTien;
		
		private System.Nullable<int> _MaDaiLy;
		
		private EntityRef<DaiLy> _DaiLy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoPhieuThuChanging(int value);
    partial void OnSoPhieuThuChanged();
    partial void OnNgayLapPhieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapPhieuChanged();
    partial void OnSoTienChanging(System.Nullable<int> value);
    partial void OnSoTienChanged();
    partial void OnMaDaiLyChanging(System.Nullable<int> value);
    partial void OnMaDaiLyChanged();
    #endregion
		
		public ThanhToan()
		{
			this._DaiLy = default(EntityRef<DaiLy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuThu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SoPhieuThu
		{
			get
			{
				return this._SoPhieuThu;
			}
			set
			{
				if ((this._SoPhieuThu != value))
				{
					this.OnSoPhieuThuChanging(value);
					this.SendPropertyChanging();
					this._SoPhieuThu = value;
					this.SendPropertyChanged("SoPhieuThu");
					this.OnSoPhieuThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapPhieu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLapPhieu
		{
			get
			{
				return this._NgayLapPhieu;
			}
			set
			{
				if ((this._NgayLapPhieu != value))
				{
					this.OnNgayLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._NgayLapPhieu = value;
					this.SendPropertyChanged("NgayLapPhieu");
					this.OnNgayLapPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Int")]
		public System.Nullable<int> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="Int")]
		public System.Nullable<int> MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					if (this._DaiLy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaiLy_ThanhToan", Storage="_DaiLy", ThisKey="MaDaiLy", OtherKey="MaDaiLy", IsForeignKey=true)]
		public DaiLy DaiLy
		{
			get
			{
				return this._DaiLy.Entity;
			}
			set
			{
				DaiLy previousValue = this._DaiLy.Entity;
				if (((previousValue != value) 
							|| (this._DaiLy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DaiLy.Entity = null;
						previousValue.ThanhToans.Remove(this);
					}
					this._DaiLy.Entity = value;
					if ((value != null))
					{
						value.ThanhToans.Add(this);
						this._MaDaiLy = value.MaDaiLy;
					}
					else
					{
						this._MaDaiLy = default(Nullable<int>);
					}
					this.SendPropertyChanged("DaiLy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
